version: "3.8"

services: 
  backendnlwheat:
    build:  .
    container_name: backendnlwheat
    ports: 
      - "4000:4000"
    command: npm run dev
    environment:
      - GITHUB_CLIENT_SECRET= //enter scret here
      - GITHUB_CLIENT_ID= //enter client id here

    volumes: 
      - .:/usr/app

    depends_on:
      - migration
  
  migration:
    build: .
    command: npx prisma migrate dev --name create_user
    volumes: 
      - .:/usr/app

      

