version: "3.8"

services: 
  backendnlwheat:
    build:  .
    container_name: backendnlwheat
    ports: 
      - "4000:4000"
    command: npm run dev
    environment:
      - GITHUB_CLIENT_SECRET=
      - GITHUB_CLIENT_ID=

    volumes: 
      - .:/usr/app
      
